# Generated by Django 4.2.4 on 2023-08-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapLocations',
            new_name='Location',
        ),
    ]
