# Generated by Django 4.2.4 on 2023-09-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['picture_order']},
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
