# Generated by Django 4.2.4 on 2023-09-05 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_location_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='image', to='places.location'),
        ),
    ]
