# Generated by Django 4.2.3 on 2023-09-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_picture_image_alter_picture_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
