# Generated by Django 4.2.3 on 2023-09-06 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_auto_20230906_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='places.location', verbose_name='Локация'),
        ),
    ]
