# Generated by Django 4.2.4 on 2023-09-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_remove_picture_number_picture_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='picture_order',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
